yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about'))
]


handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import Q, F, CheckConstraint, UniqueConstraint

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Заголовок', max_length=200)
    slug = models.SlugField('Адрес страницы', unique=True)
    description = models.TextField('Описание')

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField('Текст')
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
        db_index=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
        null=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария',
        null=True,
    )
    text = models.TextField('Текст комментария')
    created = models.DateTimeField(
        'Дата публикации комментария',
        auto_now_add=True,
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self) -> str:
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        null=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        null=True,
    )

    class Meta():
        unique_together = (('user', 'author'),)
        constraints = [
            UniqueConstraint(
                fields=['user', 'author'],
                name='follow_unique'
            ),
            CheckConstraint(check=~Q(
                user=F('author')),
                name='users_cannot_rate_themselves'),
        ]

    def __str__(self) -> str:
        return str(self.user)

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'text',
            'group',
            'image',
        ]
        help_texts = {
            'text': ('Текст нового поста'),
            'group': ('Группа, к которой будет относиться пост.'),
            'image': ('Загрузите изображение'),
        }
        labels = {
            'text': 'Текст поста',
            'group': 'Группы',
            'image': 'Картинка'
        }

    def clean_text(self):
        data = self.cleaned_data['text']
        if not data:
            raise forms.ValidationError(
                "Пожалуйста заполните поле 'Текст поста'"
            )
        return data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        help_texts = {
            'text': ('Введите текст комментария')
        }

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page
from django.contrib.auth.decorators import login_required

from .forms import CommentForm, PostForm

from .models import Group, Post, User, Follow, Comment

from yatube.settings import POSTS_OF_PAGE


def paginator_func(request, posts):
    paginator = Paginator(posts, POSTS_OF_PAGE)
    page_obj = paginator.get_page(request.GET.get('page'))
    return page_obj


# Главная страница Yatube соц сети
@cache_page(20)
def index(request):
    posts = Post.objects.all()
    context = {
        'posts': posts,
        'page_obj': paginator_func(request, posts),
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    title = Group.__str__
    context = {
        'group': group,
        'title': title,
        'page_obj': paginator_func(request, posts),
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user,
            author=author)
        context = {
            'following': following,
            'page_obj': paginator_func(request, posts),
            'posts': posts,
            'author': author,
        }
        return render(request, 'posts/profile.html', context)
    context = {
        'page_obj': paginator_func(request, posts),
        'posts': posts,
        'author': author,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    created = Comment.__str__
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
        'created': created,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if request.method == 'POST' and form.is_valid():
        new_post = form.save(commit=False)
        new_post.author = request.user
        new_post.save()
        return redirect('posts:profile', request.user)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post.pk)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('posts:post_detail', post.pk)
    context = {
        'form': form,
        'post': post,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    context = {
        'posts': posts,
        'page_obj': paginator_func(request, posts),
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/add_comment.html
<!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text }} <br> {{ comment.created }}
        </p>
      </div>
    </div>
{% endfor %}

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
  {% if post %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock title %}

{% load thumbnail %}
{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if post %}
              Редактировать пост
            {% else %}
              Новый пост
            {% endif %}         
          </div>
          {% load user_filters %}
          <div class="card-body">
            {% if post %}
            <form method="post" action="{% url 'posts:post_edit' post.id %}" enctype="multipart/form-data">
              {% else %}
              <form method="post" action="{% url 'posts:post_create' %}" enctype="multipart/form-data">
              {% endif %}
              {% csrf_token %}
              {% for field in form %}
              <input type="hidden" value="">       
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }} 
                    {% if field.field.required %}                
                      <span class="required text-danger" >*</span>                  
                    {% endif %}
                </label>
                {{ field|addclass:'form-control' }} 
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}               
              </div> 
              {% endfor %}       
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if post %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}   
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

yatube/templates/posts/follow.html
{% extends "base.html" %}

{% block title %}Посты пользователей на которых вы подписаны{% endblock title %}
{% block content %}
  <div class="container py-5 mb-5">
    {% include 'posts/includes/switcher.html' with follower=True %}
      <h1> Посты пользователей на которых вы подписаны </h1>
    <article>
      {% for post in page_obj %}
        {% include 'posts/includes/post_list.html' %}<br>
          {% if post.group.slug is not None %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    </article>
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock content %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %} {{ group.title }} {% endblock %}
{% block content %}
<div class="container py-5">
  <h1> {{ group.title }} </h1>
  <article>
    <p>
      Описание группы: <p>{{ group.description }}</p>
    </p>
    {% for post in page_obj %}
      {% include 'posts/includes/post_list.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </article>
</div>
{% endblock content %}

yatube/templates/posts/index.html
{% extends "base.html" %}

{% block title %}Последнее обновление на сайте{% endblock title %}
{% load cache %}
{% block content %}
  <div class="container py-5 mb-5">
    <h1> Последнее обновление на сайте </h1>
    <br>
    {% cache 20 index_page %}
    {% include 'posts/includes/switcher.html' %}
    <article>
      {% for post in page_obj %}
        {% include 'posts/includes/post_list.html' %}<br>
          {% if post.group.slug is not None %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% endcache %}
    </article>
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %} 
{% block title %}
Пост {{ post|truncatechars:30 }}
{% endblock  %}

{% load thumbnail %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }} 
          </li>
          {% if post.group.slug %} 
            <li class="list-group-item">
              Группа: <a href="{% url 'posts:group_list' post.group.slug %}">
              {{post.group}}
              </a>
            </li>
          {% endif %}
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора: <span>{{ post.author.posts.count }}</span>
          </li>
          {% if post.author.username %}
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author %}"> 
              все посты пользователя
            </a>
          </li>
          {% endif %}
        </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
      </p>
      <p>
        {{ post.text|linebreaksbr }}
      </p>
      {% if post.author == request.user %}
      <a class="btn btn-primary" type="submit" href="{% url 'posts:post_edit' post_id=post.id %}">
        Редактировать запись
      </a>
      {% endif %}
      {% include "posts/add_comment.html" %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}

{% block title %}
Профайл пользователя {{ author.username }}
{% endblock title %}

{% load thumbnail %}
{% block content %}
  <div class="container py-5">
    {% if user.is_authenticated %}
      <div class="mb-5">       
        <h1>Все посты пользователя {{ author.get_full_name }}</h1>
        <h3>Всего постов: {{ posts.count }}</h3>
        {% if following %}
          <a class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button">
            Отписаться
          </a>
        {% else %}
          <a class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button">
            Подписаться
          </a>
        {% endif %}
    </div>
    {% endif %}
    {% for post in page_obj %}
    <article>
        <ul>
          <li>
            Автор: {{ author.get_full_name }}
            <a href="{% url 'posts:profile' post.author %}"> все посты пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        </p>
        <p>
          {{ post.text|linebreaksbr }}
        </p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
      <p>
        {% if post.group is not None %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
      </p>
    </article>
    {% endfor %}
    
    
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock content %}